return {
    NoobiniPizzanini = { price = 100 },
    OrcaleroOrcala = { price = 350 },
    CappuccinoAssassino = { price = 750 },

    LiriliLarila = { price = 3000 },
    TrippiTroppi = { price = 5000 },

    OdinDinDinDun = { price = 7500 },

    BombardiroCrocodilo = { price = 10000 },
    LaGrandeCombination = { price = 15000 },
    ["67"] = { price = 20000 },

    CanneloniDragon = { price = 25000 }
}